# https://starship.rs/zh-CN
# 根据 schema 提供自动补全
"$schema" = 'https://starship.rs/config-schema.json'

# 在提示符之间插入空行
add_newline = false

[character]
success_symbol = '[➜](bold green) '

[directory]
disabled = false

[package]
symbol = "📦 "
disabled = true

[git_branch]
disabled = false
# format='[$symbol $branch(:$remote_branch)]($style) '
format='[$branch(:$remote_branch)]($style) '
symbol = '🌱'

[git_state]
disabled = true
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
merge =   "MG"
revert = "RVT"
# cherry_pick = "CP"
cherry_pick = "[🍒 PICKING](bold red)"
bisect = "BS"
am = "AM"
am_or_rebase = "AM/RB"
style = "yellow"

[git_metrics]
disabled=true

# https://starship.rs/zh-CN/config/#git-status
[git_status]
disabled=false
modified = '*'
untracked = '?'

[python]
disabled=false
# format='[${symbol} ${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
format='[${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
symbol = '🐍'
pyenv_version_name = false

[golang]
disabled=true

[java]
disabled=true

[nodejs]
disabled=false
format='[$symbol($version )]($style)'

[time]
disabled=true

[localip]
disabled = false
ssh_only = true
format = "[IP:$localipv4](bold red) "

[docker_context]
disabled = false
# format = '[🐋 $context ](blue bold)'
format = '[$context ](blue bold)'
